# Generated by Django 3.2.12 on 2022-04-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_asset_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='workflow',
            field=models.ManyToManyField(blank=True, to='app.Workflow'),
        ),
    ]
